import type { Lang } from "./types";

const es = {
  title: "PRISMA",
  tag: "Ordena el espectro",
  play: "Jugar",
  level: "Nivel",
  daily: "Diario",
  shop: "Tienda",
  settings: "Ajustes",
  levels: "Niveles",
  lives: "Vidas",
  coins: "Pigmentos",
  undo: "Deshacer",
  hint: "Pista",
  extra: "Tubo extra",
  extraShort: "Extra",
  next: "Siguiente",
  retry: "Reintentar",
  home: "Inicio",
  resume: "Seguir",
  pause: "Pausa",
  restart: "Reiniciar",
  win: "Espectro resuelto",
  noLives: "Sin vidas",
  nextLife: "Siguiente vida",
  watchAd: "Ver anuncio",
  claim: "Reclamar",
  sponsored: "Espacio para anuncio",
  adBody: "Aquí irá tu red de anuncios. Por ahora es una simulación de 3 segundos para probar el loop de recompensa.",
  notEnough: "Pigmentos insuficientes",
  bought: "Listo",
  muted: "Silencio",
  shake: "Temblor",
  language: "Idioma",
  spanish: "Español",
  english: "English",
  how: "Arrastra el pigmento al tubo vacío.",
  veil: "Eclipse: un tubo esconde el pigmento hasta que lo tocas.",
  dailyTitle: "Desafío del día",
  dailyDone: "Completado hoy",
  dailyPlay: "Jugar el diario",
  extraLife: "+1 vida",
  packUndo: "Deshacer ×5",
  packHint: "Pista ×3",
  packExtra: "Tubo extra ×1",
  removeAds: "Quitar anuncios",
  owned: "Activo",
  stuck: "¿Atascado?",
  stuckBody: "Usa una pista, un tubo extra o deshacer.",
  stars: "estrellas",
  reward: "Recompensa",
  continue: "Continuar",
  newBest: "Nuevo récord de nivel",
  of: "de",
  ch1: "Alba",
  ch2: "Tinta",
  ch3: "Prisma",
  ch4: "Eclipse",
  ch5: "Absoluto",
  dailyLead: "Un espectro distinto cada día. Vuelve mañana.",
  stats: "Este dispositivo",
  statsHint: "Solo tu teléfono. Gente real se ve en Poki o Plausible.",
  sessions: "Sesiones",
  combo: "Racha",
  privacy: "Privacidad",
};

const en: typeof es = {
  title: "PRISMA",
  tag: "Sort the spectrum",
  play: "Play",
  level: "Level",
  daily: "Daily",
  shop: "Shop",
  settings: "Settings",
  levels: "Levels",
  lives: "Lives",
  coins: "Pigment",
  undo: "Undo",
  hint: "Hint",
  extra: "Extra tube",
  extraShort: "Extra",
  next: "Next",
  retry: "Retry",
  home: "Home",
  resume: "Resume",
  pause: "Pause",
  restart: "Restart",
  win: "Spectrum solved",
  noLives: "No lives",
  nextLife: "Next life",
  watchAd: "Watch ad",
  claim: "Claim",
  sponsored: "Ad slot",
  adBody: "Your ad network goes here. This is a 3-second reward simulation so the loop is playable today.",
  notEnough: "Not enough pigment",
  bought: "Ready",
  muted: "Mute",
  shake: "Screen shake",
  language: "Language",
  spanish: "Español",
  english: "English",
  how: "Drag the pigment into the empty vial.",
  veil: "Eclipse: one vial hides its pigment until you touch it.",
  dailyTitle: "Daily challenge",
  dailyDone: "Done today",
  dailyPlay: "Play daily",
  extraLife: "+1 life",
  packUndo: "Undo ×5",
  packHint: "Hint ×3",
  packExtra: "Extra tube ×1",
  removeAds: "Remove ads",
  owned: "Owned",
  stuck: "Stuck?",
  stuckBody: "Use a hint, an extra tube, or undo.",
  stars: "stars",
  reward: "Reward",
  continue: "Continue",
  newBest: "New level record",
  of: "of",
  ch1: "Dawn",
  ch2: "Ink",
  ch3: "Prism",
  ch4: "Eclipse",
  ch5: "Absolute",
  dailyLead: "A different spectrum every day. Come back tomorrow.",
  stats: "This device",
  statsHint: "Only this phone. Live players show in Poki or Plausible.",
  sessions: "Sessions",
  combo: "Streak",
  privacy: "Privacy",
};

export type Copy = typeof es;

export function t(lang: Lang): Copy {
  return lang === "en" ? en : es;
}
